config/routes.rb
Rails.application.routes.draw do
  # get 'customers/new'
  # get 'customers/create'
  get 'customers/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Define rutas para productos
  resources :products, only: [:index, :show]

  # Define rutas para páginas estáticas
  get '/pages/:title', to: 'pages#show', as: 'page'
  get 'about', to: 'pages#about', as: :about

  # Rutas para el carrito
  # resource :cart, only: [:show] do
  #   patch :update, to: 'carts#update_quantity', as: :update
  #   delete :remove, to: 'carts#remove_item', as: :remove
  # end

  # resources :carts, only: [:show] do
  #   post :checkout, to: 'carts#create_order', as: :create_order
  # end

  resource :cart, only: [:show] do
    post :add, to: 'carts#add_to_cart', as: :add_to_cart
    patch :update, to: 'carts#update_quantity', as: :update
    delete :remove, to: 'carts#remove_item', as: :remove
    post :checkout, to: 'carts#create_order', as: :create_order
  end

  # Ruta personalizada para agregar al carrito
  post 'cart/add', to: 'carts#add_to_cart', as: 'add_to_cart'

  # Ruta raíz
  root "products#index"

  get 'checkout', to: 'carts#checkout_form', as: 'checkout'

  resources :customers, only: [:new, :create]
  # get 'checkout', to: 'checkout#index'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  resources :orders, only: [:create, :show]

  get 'contact', to: 'pages#contact', as: :contact

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoraStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "bulma.min", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  </head>

  <body>
    <div class="container">
      <%# Level 1 %>
      <nav class="level mb-0 pb-0 has-background-white-ter">
        <div class="level-left">

        </div>

        <div class="level-right">
          <div class="level-item">
              <a href="">
                <span class="icon">
                  <i class="fa-solid fa-user has-text-success"></i>
                </span>
              </a>
          </div>

          <div class="level-item">
            <% if customer_signed_in? %>
              <p class="subtitle is-5">Welcome <%= current_customer.first_name %> ! </p>
              <%= button_to 'Sign out', destroy_customer_session_path, method: :delete %>
              <%# , class: "button is-success" %>
            <% else %>
              <%= button_to 'Login', new_customer_session_path %>
            <% end %>
          </div>
          <div class="level-item">
            <%= link_to contact_path do %>
              <span class="icon">
                <i class="fa-solid fa-location-dot has-text-success"></i>
              </span>
            <% end %>
          </div>

          <div class="level-item">

              <%= link_to cart_path do %>
                <span class="icon">
                  <i class="fa-sharp fa-solid fa-bag-shopping has-text-success"></i>
                </span>
              <% end %>

          </div>
        </div>
      </nav>

      <%# Level 2 %>
      <div class="level has-background-white-ter">
        <div class="level-left">

          <div class="level-item">
            <%= link_to root_path do %>
              <figure class="image is-128x128">
                <img src="/assets/logoDora.png" alt="Dora Jewelry Logo" />
              </figure>
            <% end %>
          </div>

          <%# <div class="level-item"> %>
            <% ["Rings", "Charms", "Earrings", "Bracelets", "Necklaces"].each do |category| %>
              <div class="level-item">
                <%= link_to category, products_path(category: category),
                            class: "has-text-grey-darker has-text-weight-semibold is-uppercase #{'has-text-success' if params[:category] == category}" %>
              </div>
            <% end %>
         <%# </div> %>
        </div>

        <div class="level-right">

          <div class="level-item">
            <%= link_to 'ABOUT US', about_path, class: 'has-text-success' %>
          </div>

          <div class="level-item">
            <%= link_to 'CONTACT US', contact_path, class: 'has-text-success' %>
          </div>

          <div class="level-item">
            <div class="field has-addons">
              <%= form_with url: products_path, method: :get, local: true, class: "field has-addons" do %>
                <div class="control">
                  <%= text_field_tag :query, params[:query],
                                    class: "input is-small has-background-white",
                                    placeholder: "Find product" %>
                </div>
                <div class="control">
                  <%= submit_tag "Search", class: "button is-success" %>
                </div>
              <% end %>
            </div>
         </div>
       </div>
     </div>

      <%# Banner %>
      <section class="hero is-medium custom-background">
        <div class="hero-body">
          <div class="container has-text-left">
          <p class="title">BLACK FRIDAY</p>
          <p class="subtitle has-text-black is-regular">Save 30% Sitewide</p>
          </div>
        </div>
      </section>

      <%= yield %>

      <%= link_to "https://wa.me/14313749792?text=Hi%20Dora%20I%20like%20to%20to%20know%20more%20about%20your%20jewelry%20collection." do %>
        <div class="whatsapp-button">
          <img src="/assets/whatsapp.png" alt="WhatsApp" />
        </div>
      <% end %>


      <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>.
            The source code is licensed
            <a href="https://opensource.org/license/mit">MIT</a>. The
            website content is licensed
            <a href="https://creativecommons.org/licenses/by-nc-sa/4.0//">CC BY NC SA 4.0</a>
          </p>
        </div>
      </footer>
    </div>
  </body>
</html>